#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
# Walks through the RevenueCat DASHBOARD side of "Buy Pro on Web" (issue #24):
# a one-time Pro product on the Web Billing app, the `pro` entitlement, the
# starter bundle of SCAN virtual currency, and the offering package the Web
# paywall reads. It builds on what #5 already set up (a Web Billing app linked
# to a Stripe Sandbox, and the shared `default` offering that also holds
# Android's Test Store packages). Nothing here is secret, and nothing is
# written by this wizard: the values land in web/.env.* via the companion
# wizard scripts/wizard_web_revenuecat.sh, which it offers to run at the end.
#
# Menu names below come from RevenueCat's docs (Product catalog > Products /
# Entitlements / Offerings / In-App Currencies; Apps & Providers >
# Configurations). The dashboard changes over time, so each stage says what to
# look for rather than relying on an exact label.

TOTAL_STAGES=7
ENV_FILE="/dev/null" # this wizard writes no env file; keeps ask from reading a stray .env
RC_PROJECT_ID="proj07f52826" # workers/scan-proxy/wrangler.toml REVENUECAT_PROJECT_ID
RC_URL="https://app.revenuecat.com/projects/${RC_PROJECT_ID}"

if [[ ! -d web || ! -d workers/scan-proxy ]]; then
  warn "Run this from the repo root (the folder that contains web/ and workers/)."
  exit 1
fi

banner "RevenueCat dashboard: set up Buy Pro on Web"

stage "What we're setting up"
say "In the RevenueCat dashboard, you will:"
step "make sure the Web Billing app exists (it should from the #5 prototype)"
step "create a one-time 'Pro' product on it"
step "attach that product to a 'pro' entitlement"
step "have buying it grant a starter bundle of SCAN (scan credits)"
step "put it on the offering's lifetime package, next to Android's product"
step "hand off to the second wizard, which saves the ids into web/.env.local"
say ""
note "Prices and the starter bundle size are placeholders until launch pricing is set (ADR-0006)."
note "Safe to stop and re-run: each stage tells you what to check if you already did it."
open_url "$RC_URL"
pause "RevenueCat project open in your browser? Press Enter"

stage "The Web Billing app"
say "From #5 you already have a Web Billing app linked to a Stripe Sandbox."
step "In the left menu open 'Apps & Providers', then 'Configurations'."
step "Open the web configuration. You should see a sandbox public key starting rcb_sb_."
step "If there is no web configuration, create one (RevenueCat will ask you to link Stripe)."
note "A real Stripe account is only needed to go live. A Stripe Sandbox is fine for now."
pause "Web configuration present? Press Enter"

stage "Create the Pro product"
say "A one-time purchase that can only be bought once, i.e. a lifetime unlock."
step "Open 'Product catalog', then the 'Products' tab."
step "Click '+ New' next to your WEB billing configuration (not the Android/Test Store one)."
step "Product type: 'Non-consumable' (NOT consumable, NOT subscription)."
step "Identifier: suggested 'rigcheck_pro_lifetime' (you can't change it later)."
step "Name: 'RigCheck Pro'. Description: 'One-time lifetime unlock'."
step "Price: any placeholder, for example 9.99 USD. Launch pricing comes later."
step "Save."
ask PRO_PRODUCT_ID "Product identifier you used [rigcheck_pro_lifetime]:"
PRO_PRODUCT_ID="${PRO_PRODUCT_ID:-rigcheck_pro_lifetime}"
say "Using '$PRO_PRODUCT_ID' in the next steps."
pause "Product created? Press Enter"

stage "The 'pro' entitlement"
say "The Web app decides Free vs Pro from an active entitlement named 'pro'."
step "In 'Product catalog', open the 'Entitlements' tab."
step "If there is no 'pro' entitlement: '+ New entitlement', identifier exactly 'pro'."
step "Open 'pro' and click 'Attach'. Attach '$PRO_PRODUCT_ID' (the Web product)."
say ""
say "Pro bought on Android is supposed to count on Web too (one purchase per household)."
step "Optional but intended: also attach Android's lifetime product (today the Test Store 'Lifetime') to 'pro'."
note "Skipping this only means Android lifetime buyers don't show as Pro on Web yet."
note "If you used a different entitlement id than 'pro', the next wizard asks for it."
pause "Entitlement attached? Press Enter"

stage "Starter scans (SCAN virtual currency)"
say "Buying Pro should add a starter bundle of scans to the buyer's balance."
say "Android already uses the 'SCAN' currency; Web reads the same balance."
step "In 'Product catalog', open 'In-App Currencies' and open the SCAN currency."
step "Under associated products click 'Add associated product'."
step "Select '$PRO_PRODUCT_ID' and enter the amount granted on purchase."
step "For now use a small placeholder like 5. The real number is a launch pricing decision."
step "Save."
note "Rule for later (ADR-0006): the Pro bundle must net at least 5x the worst-case scan cost (about \$0.016)."
note "The Web app never grants scans itself; it only shows the balance RevenueCat reports."
pause "Currency association saved? Press Enter"

stage "Put Pro on the offering's lifetime package"
say "The Web paywall reads an offering and buys its 'lifetime' package."
say "From #5, the shared 'default' offering already has Android's Lifetime package."
step "In 'Product catalog', open the 'Offerings' tab, then open the 'default' offering."
step "Open the existing Lifetime package ('\$rc_lifetime') and attach '$PRO_PRODUCT_ID' to it as well."
note "One package can hold a product per platform. This keeps Android and Web on one package."
warn "If you made a separate new package instead, note its identifier: the next wizard asks for it."
step "Make sure this offering is the project's default/current offering."
pause "Package updated? Press Enter"

stage "Save the ids into the Web app"
say "The companion wizard stores the public key and ids in web/.env.local (and, if you choose,"
say "web/.env.production), refusing secret keys and flagging a sandbox key bound for the live site."
if confirm "Run scripts/wizard_web_revenuecat.sh now?"; then
  exec bash scripts/wizard_web_revenuecat.sh
else
  SKIPPED+=("run scripts/wizard_web_revenuecat.sh to save the public key and offering id into web/.env.local")
fi

finish
say "Then check it works:"
step "cd web && npm run dev, sign in, open Account: the plan, price and 'Buy Pro' should show."
step "Use RevenueCat's sandbox test card, buy Pro, and watch 'Pro plan' and your scans appear."
step "Then do the real cancel test in issue #11 before shipping."
