#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Public values that already live in the Android source; the wizard reads them
# from there so there is one place to change them.
KT_BACKEND="android/app/src/main/java/com/rigcheck/app/data/SupabaseAccountBackend.kt"
KT_GOOGLE="android/app/src/main/java/com/rigcheck/app/data/GoogleSignIn.kt"
[[ -f "$KT_BACKEND" && -f "$KT_GOOGLE" ]] || { echo "Run this from the repo root." >&2; exit 1; }
SUPABASE_URL=$(grep -oE 'SUPABASE_URL = "[^"]+"' "$KT_BACKEND" | cut -d'"' -f2)
SUPABASE_KEY=$(grep -oE 'SUPABASE_PUBLISHABLE_KEY = "[^"]+"' "$KT_BACKEND" | cut -d'"' -f2)
SUPABASE_REF=${SUPABASE_URL#https://}; SUPABASE_REF=${SUPABASE_REF%%.*}
[[ -n "$SUPABASE_URL" && -n "$SUPABASE_KEY" ]] || { echo "Couldn't read the Supabase config from $KT_BACKEND." >&2; exit 1; }

banner "Android sign-in: Google and Apple (#22)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Supabase: allow the app's return link"
say "Apple sign-in opens a browser tab and returns to the app through rigcheck://login."
say "Supabase refuses redirects that aren't on its allow list."
open_url "https://supabase.com/dashboard/project/$SUPABASE_REF/auth/url-configuration"
step "Under 'Redirect URLs' click 'Add URL'."
step "Enter exactly:  rigcheck://login"
step "Click 'Save changes'. Leave 'Site URL' alone (the Web app uses it)."
pause "Done? Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: the Web OAuth client"
say "Supabase checks Google's ID token against a *Web application* client."
open_url "https://console.cloud.google.com/apis/credentials"
step "Pick (or create) the Google Cloud project for RigCheck."
step "If asked, finish the 'OAuth consent screen' first (External, app name RigCheck, your email)."
step "Create credentials → OAuth client ID → Application type: Web application."
step "Authorized redirect URI:  $SUPABASE_URL/auth/v1/callback"
step "Create, then copy the Client ID and the Client secret."
ask GOOGLE_WEB_CLIENT_ID "Paste the Web client ID (ends .apps.googleusercontent.com):"
ask_secret GOOGLE_WEB_CLIENT_SECRET "Paste the Web client secret (hidden):"
[[ "$GOOGLE_WEB_CLIENT_ID" == *.apps.googleusercontent.com ]] || warn "That doesn't look like a Google client ID; double-check it."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: the Android OAuth client"
say "Google only issues ID tokens to an app it can recognise by package name + signing key."
if command -v keytool >/dev/null 2>&1 && [[ -f "$HOME/.android/debug.keystore" ]]; then
  note "Debug-build SHA-1 (from your local debug keystore):"
  keytool -list -v -keystore "$HOME/.android/debug.keystore" -alias androiddebugkey \
    -storepass android -keypass android 2>/dev/null | grep -E 'SHA1:' | sed 's/^ */    /' || true
else
  note "keytool or the debug keystore wasn't found; run 'gradlew signingReport' in android/ to get the SHA-1."
fi
open_url "https://console.cloud.google.com/apis/credentials"
step "Create credentials → OAuth client ID → Application type: Android."
step "Package name:  com.rigcheck.app"
step "SHA-1 certificate fingerprint: the debug value above (add the Play app-signing SHA-1 later for release)."
step "Create. You don't need to copy anything from this one."
pause "Done? Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Supabase: turn on the Google provider"
open_url "https://supabase.com/dashboard/project/$SUPABASE_REF/auth/providers"
step "Open 'Google' and switch 'Enable Sign in with Google' on."
step "Client IDs:  $GOOGLE_WEB_CLIENT_ID"
step "Client Secret:  the Web client secret you just copied."
step "Leave 'Skip nonce checks' OFF (the app sends a nonce)."
step "Save."
pause "Done? Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Apple: Services ID and key, then Supabase"
say "Apple needs an Apple Developer account (paid). This is the longest step."
say "Follow Supabase's own walkthrough, which stays current with Apple's console:"
open_url "https://supabase.com/docs/guides/auth/social-login/auth-apple"
say "You will create, in order: an App ID, a Services ID, and a Sign in with Apple key."
step "Use  $SUPABASE_URL/auth/v1/callback  as the Services ID's return URL."
step "Generate the client-secret JWT from the key as the guide describes."
open_url "https://supabase.com/dashboard/project/$SUPABASE_REF/auth/providers"
step "Open 'Apple', enable it, paste the Services ID and the generated secret, Save."
warn "Apple's generated secret expires (at most every 6 months); set yourself a reminder."
pause "Apple enabled in Supabase? Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Put the Web client ID in the app, then check Supabase"
say "The Web client ID is public (like the Supabase key), so it goes in the source."
if grep -q 'GOOGLE_WEB_CLIENT_ID = ""' "$KT_GOOGLE"; then
  sed -i "s|GOOGLE_WEB_CLIENT_ID = \"\"|GOOGLE_WEB_CLIENT_ID = \"$GOOGLE_WEB_CLIENT_ID\"|" "$KT_GOOGLE"
  if grep -qF "GOOGLE_WEB_CLIENT_ID = \"$GOOGLE_WEB_CLIENT_ID\"" "$KT_GOOGLE"; then
    printf '  %s✓ set%s GOOGLE_WEB_CLIENT_ID in %s\n' "$GREEN" "$RESET" "$KT_GOOGLE"
  else
    warn "Edit didn't take; set GOOGLE_WEB_CLIENT_ID in $KT_GOOGLE by hand."
  fi
elif grep -qF "GOOGLE_WEB_CLIENT_ID = \"$GOOGLE_WEB_CLIENT_ID\"" "$KT_GOOGLE"; then
  note "Already set to that value."
else
  warn "GOOGLE_WEB_CLIENT_ID in $KT_GOOGLE already has a different value; leaving it alone."
fi

say "Asking Supabase which providers are live..."
settings=$(curl -fsS -H "apikey: $SUPABASE_KEY" "$SUPABASE_URL/auth/v1/settings" 2>/dev/null || true)
for provider in email google apple; do
  if grep -qE "\"$provider\" *: *true" <<<"$settings"; then
    printf '  %s✓%s %s is enabled\n' "$GREEN" "$RESET" "$provider"
  else
    warn "$provider does not show as enabled (or Supabase couldn't be reached)."
  fi
done
say "Then build and run the app, tap Scan Photo → 'Continue with Google' and 'Continue with Apple'."
say "Commit the GoogleSignIn.kt change when it works."
# ──────────────────────────────────────────────────────────────────────────

finish
