#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
# Sets the VITE_REVENUECAT_* values the Web "Buy Pro" paywall reads, in
# web/.env.local (sandbox, for local runs) and, optionally, web/.env.production
# (the live site). Run from the repo root. Values here are all public by design
# (the RevenueCat PUBLIC Web Billing key, never the secret key).

TOTAL_STAGES=5
LOCAL_ENV="web/.env.local"
PROD_ENV="web/.env.production"
RC_PROJECT_ID="proj07f52826" # workers/scan-proxy/wrangler.toml REVENUECAT_PROJECT_ID

# check_public_key VALUE: refuse a secret key outright, warn on an unexpected prefix.
# Returns 0 if the key may be used, 1 if it must be re-entered.
check_public_key() {
  local key="$1"
  if [[ -z "$key" ]]; then
    warn "That was empty."
    return 1
  fi
  if [[ "$key" == sk_* ]]; then
    warn "That looks like a SECRET key (sk_...). It must never go in the Web app. Use the Web Billing PUBLIC key."
    return 1
  fi
  if [[ "$key" != rcb_* ]]; then
    warn "Web Billing public keys normally start with rcb_. This one starts differently; it may be an Android/iOS key."
    confirm "Use it anyway?" || return 1
  fi
  return 0
}

# ask_public_key KEY "Prompt": ask until check_public_key accepts the value.
ask_public_key() {
  local key="$1" prompt="$2"
  while true; do
    ask "$key" "$prompt"
    if check_public_key "${!key}"; then return 0; fi
  done
}

if [[ ! -d web || ! -d workers/scan-proxy ]]; then
  warn "Run this from the repo root (the folder that contains web/ and workers/)."
  exit 1
fi

banner "Web Billing: VITE_REVENUECAT_* setup"

stage "Where things stand"
say "The Web paywall needs two values to switch on; without them it hides purchases."
for f in "$LOCAL_ENV" "$PROD_ENV"; do
  say "$f:"
  for k in VITE_REVENUECAT_WEB_PUBLIC_API_KEY VITE_REVENUECAT_WEB_OFFERING_ID VITE_REVENUECAT_PRO_ENTITLEMENT_ID VITE_REVENUECAT_PRO_PACKAGE_ID; do
    ENV_FILE="$f"
    if v=$(_existing "$k") && [[ -n "$v" ]]; then
      if [[ "$k" == *API_KEY ]]; then note "    $k = ${v:0:8}... (set)"; else note "    $k = $v"; fi
    else
      note "    $k = (not set)"
    fi
  done
done
say ""
say "Needed from RevenueCat: a Web Billing app's PUBLIC key, the offering's id, and"
say "(if not 'pro') the Pro entitlement id. Nothing here is secret."
pause "Press Enter to continue"

stage "RevenueCat: the Web Billing public key (sandbox)"
ENV_FILE="$LOCAL_ENV"
say "RevenueCat project id (the same one Android and the scan Worker use): $RC_PROJECT_ID"
open_url "https://app.revenuecat.com/projects/${RC_PROJECT_ID}"
step "In the left menu open 'Apps & Providers', then 'Configurations', then the web configuration."
step "If there is no web configuration yet, create one (RevenueCat will ask you to link Stripe first)."
step "Copy the SANDBOX public API key. It starts with rcb_sb_ and is the one to use locally."
note "The same page also shows the production key (rcb_...). Dashboard labels move around over time."
warn "Do NOT copy a secret key (sk_...). The Android/Test Store key is a different key; do not use it here."
while true; do
  ask_public_key VITE_REVENUECAT_WEB_PUBLIC_API_KEY "Paste the Web Billing public key (sandbox):"
  if [[ "$VITE_REVENUECAT_WEB_PUBLIC_API_KEY" == rcb_sb_* ]]; then break; fi
  warn "That is not a sandbox key (sandbox keys start rcb_sb_). Local runs with it could take real payments."
  confirm "Use it locally anyway?" && break
done
write_env VITE_REVENUECAT_WEB_PUBLIC_API_KEY "$VITE_REVENUECAT_WEB_PUBLIC_API_KEY"

stage "RevenueCat: the offering id"
ENV_FILE="$LOCAL_ENV"
open_url "https://app.revenuecat.com/projects/${RC_PROJECT_ID}"
step "In the left menu open 'Product catalog', then the 'Offerings' tab."
step "Open (or create) the offering the Web paywall should read. The shared one from #5 is 'default'."
step "It must contain a package for the lifetime Pro product, and that product must be a Web Billing product."
step "Copy the offering's Identifier (for example 'default'), not its display name."
ask VITE_REVENUECAT_WEB_OFFERING_ID "Offering identifier:"
if [[ -z "$VITE_REVENUECAT_WEB_OFFERING_ID" ]]; then
  warn "Empty: skipping. The paywall stays hidden until this is set; re-run the wizard to add it."
  SKIPPED+=("VITE_REVENUECAT_WEB_OFFERING_ID (the paywall stays hidden without it)")
else
  write_env VITE_REVENUECAT_WEB_OFFERING_ID "$VITE_REVENUECAT_WEB_OFFERING_ID"
fi

stage "RevenueCat: the Pro entitlement and package (optional)"
ENV_FILE="$LOCAL_ENV"
open_url "https://app.revenuecat.com/projects/${RC_PROJECT_ID}"
step "In 'Product catalog', open the 'Entitlements' tab."
step "Check there is an entitlement for Pro and that the lifetime Web Billing product is attached to it."
step "The Web app assumes the entitlement id is 'pro'. If yours differs, copy its Identifier."
say "Leave a prompt blank to accept the default."
ask VITE_REVENUECAT_PRO_ENTITLEMENT_ID "Pro entitlement identifier [pro]:"
if [[ -n "$VITE_REVENUECAT_PRO_ENTITLEMENT_ID" && "$VITE_REVENUECAT_PRO_ENTITLEMENT_ID" != "pro" ]]; then
  write_env VITE_REVENUECAT_PRO_ENTITLEMENT_ID "$VITE_REVENUECAT_PRO_ENTITLEMENT_ID"
fi
say ""
say "By default the Web app buys the offering's 'lifetime' package. Only set a package"
say "id if the Pro package is NOT the lifetime-type package in that offering."
ask VITE_REVENUECAT_PRO_PACKAGE_ID "Pro package identifier [blank = lifetime package]:"
if [[ -n "$VITE_REVENUECAT_PRO_PACKAGE_ID" ]]; then
  write_env VITE_REVENUECAT_PRO_PACKAGE_ID "$VITE_REVENUECAT_PRO_PACKAGE_ID"
fi

stage "The live site (web/.env.production), optional"
say "web/.env.production is committed and baked into the live Cloudflare Pages build."
warn "Only put the PRODUCTION Web Billing key here. A sandbox key would put test checkout on the live site."
if confirm "Write the live-site values now?"; then
  ENV_FILE="$PROD_ENV"
  step "On the same web configuration page, copy the PRODUCTION public API key (starts rcb_, not rcb_sb_)."
  note "If only a sandbox key shows, the configuration may not be linked to a real Stripe account yet."
  while true; do
    ask_public_key VITE_REVENUECAT_WEB_PUBLIC_API_KEY "Paste the Web Billing PRODUCTION public key:"
    if [[ "$VITE_REVENUECAT_WEB_PUBLIC_API_KEY" == rcb_sb_* ]]; then
      warn "That is a SANDBOX key (rcb_sb_). It must not go in the live-site file. Paste the production key."
      continue
    fi
    break
  done
  write_env VITE_REVENUECAT_WEB_PUBLIC_API_KEY "$VITE_REVENUECAT_WEB_PUBLIC_API_KEY"
  if [[ -n "$VITE_REVENUECAT_WEB_OFFERING_ID" ]]; then
    write_env VITE_REVENUECAT_WEB_OFFERING_ID "$VITE_REVENUECAT_WEB_OFFERING_ID"
  else
    SKIPPED+=("VITE_REVENUECAT_WEB_OFFERING_ID in $PROD_ENV (no offering id captured)")
  fi
  if [[ -n "$VITE_REVENUECAT_PRO_ENTITLEMENT_ID" && "$VITE_REVENUECAT_PRO_ENTITLEMENT_ID" != "pro" ]]; then
    write_env VITE_REVENUECAT_PRO_ENTITLEMENT_ID "$VITE_REVENUECAT_PRO_ENTITLEMENT_ID"
  fi
  if [[ -n "$VITE_REVENUECAT_PRO_PACKAGE_ID" ]]; then
    write_env VITE_REVENUECAT_PRO_PACKAGE_ID "$VITE_REVENUECAT_PRO_PACKAGE_ID"
  fi
  note "$PROD_ENV is tracked by git: review the diff and commit it when you are ready to ship."
else
  SKIPPED+=("$PROD_ENV: not written (the live site keeps purchases hidden until it is)")
fi

finish
say "Next:"
step "Restart the Web dev server (cd web && npm run dev) to pick up $LOCAL_ENV."
step "Sign in and open Account: you should see your plan and a 'Buy Pro' button."
step "Before shipping, do the real sandbox cancel test in issue #11."
note "Pro must also grant the starter SCAN bundle in RevenueCat; the Web app only reads the balance."
