#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
# Sets up the two live test accounts the scan-proxy Weekly and Release suites
# sign in as (#21): a funded one and a no-credits one. Each is a Supabase user
# whose RevenueCat customer is named by the user's UUID. The funded user is the
# one scripts/wizard_web_external_test_user.sh creates; this wizard adds the
# second user and the RevenueCat side of both.
#
# No stage opens a browser: each prints the page to open yourself.

TOTAL_STAGES=6
ENV_FILE="web/.env.local"
PROJECT_REF="lifginpapkevreyrzzex"
RC_PROJECT_ID="proj07f52826"

# show_url URL prints a page for the human to open in their own browser.
show_url() { printf '  %s→ open in your browser:%s %s\n' "$GREEN" "$RESET" "$1"; }

# sign_in EMAIL PASSWORD prints the sign-in response body; returns non-zero unless HTTP 200.
sign_in() {
  local url key out code
  url=$(_existing VITE_SUPABASE_URL || true)
  key=$(_existing VITE_SUPABASE_PUBLISHABLE_KEY || true)
  [[ -n "$url" && -n "$key" ]] || return 1
  out=$(curl -s -w '\n%{http_code}' -X POST "${url}/auth/v1/token?grant_type=password" \
    -H "apikey: ${key}" -H "Content-Type: application/json" \
    -d "$(printf '{"email":"%s","password":"%s"}' "$1" "$2")") || return 1
  code="${out##*$'\n'}"
  printf '%s' "${out%$'\n'*}"
  [[ "$code" == "200" ]]
}

# user_id_of BODY pulls the user's UUID out of a sign-in response.
user_id_of() {
  printf '%s' "$1" | sed -n 's/.*"user":{"id":"\([^"]*\)".*/\1/p'
}

banner "Live test accounts for the scan-proxy Weekly and Release suites"

stage "Check the funded test user already exists"
say "The 'funded' account is the Web External suite's test user."
FUNDED_EMAIL=$(_existing WEB_EXTERNAL_TEST_EMAIL || true)
FUNDED_PASSWORD=$(_existing WEB_EXTERNAL_TEST_PASSWORD || true)
if [[ -z "$FUNDED_EMAIL" || -z "$FUNDED_PASSWORD" ]]; then
  warn "WEB_EXTERNAL_TEST_EMAIL / WEB_EXTERNAL_TEST_PASSWORD are missing from $ENV_FILE."
  say "Run scripts/wizard_web_external_test_user.sh first, then re-run this wizard."
  exit 1
fi
printf '  %s✓ found%s funded test user: %s\n' "$GREEN" "$RESET" "$FUNDED_EMAIL"
pause "Press Enter to continue"

stage "Supabase: create the second (no-credits) test user"
say "This user stays at zero Scan Credit, so scans as it get 402 insufficient_credits."
show_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/users"
step "Click 'Add user' -> 'Create new user'."
step "Email: a different address from the funded user, e.g. you+rigcheck-nocredits@gmail.com."
step "Password: a strong throwaway one; keep it handy for the next stage."
step "Tick 'Auto Confirm User', then click 'Create user'."
step "Check the new row shows as confirmed."
pause "User created? Press Enter"

stage "Save the no-credits credentials"
say "These go only into $ENV_FILE (gitignored). Never commit them."
ask WEB_EXTERNAL_TEST_NOCREDITS_EMAIL "No-credits user email:"
ask_secret WEB_EXTERNAL_TEST_NOCREDITS_PASSWORD "No-credits user password (hidden):"
write_env WEB_EXTERNAL_TEST_NOCREDITS_EMAIL "$WEB_EXTERNAL_TEST_NOCREDITS_EMAIL"
write_env WEB_EXTERNAL_TEST_NOCREDITS_PASSWORD "$WEB_EXTERNAL_TEST_NOCREDITS_PASSWORD"

stage "Sign both users in and read their UUIDs"
say "Each user's UUID is the RevenueCat customer id the Worker will spend."
FUNDED_ID=""
NOCREDITS_ID=""
if body=$(sign_in "$FUNDED_EMAIL" "$FUNDED_PASSWORD"); then
  FUNDED_ID=$(user_id_of "$body")
  printf '  %s✓ funded sign-in works%s\n' "$GREEN" "$RESET"
else
  warn "funded user sign-in failed; check its credentials in $ENV_FILE"
fi
if body=$(sign_in "$WEB_EXTERNAL_TEST_NOCREDITS_EMAIL" "$WEB_EXTERNAL_TEST_NOCREDITS_PASSWORD"); then
  NOCREDITS_ID=$(user_id_of "$body")
  printf '  %s✓ no-credits sign-in works%s\n' "$GREEN" "$RESET"
else
  warn "no-credits user sign-in failed; check its credentials in $ENV_FILE"
fi
if [[ -z "$FUNDED_ID" || -z "$NOCREDITS_ID" ]]; then
  say "Couldn't read a UUID automatically. Copy it from the Supabase users table (the 'UID' column):"
  show_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/users"
  [[ -n "$FUNDED_ID" ]] || { printf -v prompt 'UUID of %s:' "$FUNDED_EMAIL"; ask FUNDED_ID "$prompt"; }
  [[ -n "$NOCREDITS_ID" ]] || { printf -v prompt 'UUID of %s:' "$WEB_EXTERNAL_TEST_NOCREDITS_EMAIL"; ask NOCREDITS_ID "$prompt"; }
fi
note "funded:     $FUNDED_ID"
note "no-credits: $NOCREDITS_ID"
pause "These look right? Press Enter"

stage "RevenueCat: create both customers"
say "RevenueCat only creates a customer when it first sees one. A single read with a"
say "PUBLIC SDK key does that (the same way smoke-test-user was made)."
show_url "https://app.revenuecat.com/"
step "Open your project's API keys page and copy a PUBLIC SDK key (not the secret key)."
note "The exact menu names may differ; you want the key your apps embed, which is safe to paste here."
ask RC_PUBLIC_SDK_KEY "Public SDK key:"
for pair in "funded:$FUNDED_ID" "no-credits:$NOCREDITS_ID"; do
  label="${pair%%:*}"; id="${pair#*:}"
  code=$(curl -s -o /dev/null -w '%{http_code}' \
    "https://api.revenuecat.com/v1/subscribers/${id}" \
    -H "Authorization: Bearer ${RC_PUBLIC_SDK_KEY}" -H "Content-Type: application/json" || echo 000)
  if [[ "$code" == "200" || "$code" == "201" ]]; then
    printf '  %s✓ %s customer ready (HTTP %s)%s\n' "$GREEN" "$label" "$code" "$RESET"
  else
    warn "$label customer request returned HTTP $code"
    SKIPPED+=("RevenueCat customer for the $label user ($id): create it, then re-run this stage")
  fi
done
pause "Press Enter to continue"

stage "RevenueCat: give the funded customer a SCAN balance"
say "Only the FUNDED customer gets credits. Leave the no-credits customer at zero."
show_url "https://app.revenuecat.com/projects/${RC_PROJECT_ID}/customers"
step "Search for the funded customer's UUID: $FUNDED_ID"
step "Open that customer and grant it SCAN virtual currency, e.g. 50 (each live scan case spends 1)."
note "The grant lives on the customer's page, as it did for smoke-test-user; exact labels may differ."
step "Open the no-credits customer ($NOCREDITS_ID) and confirm its SCAN balance is 0 or empty."
pause "Balance granted? Press Enter"

RC_SECRET=${REVENUECAT_SECRET_KEY:-}
if [[ -n "$RC_SECRET" ]]; then
  say "Reading the funded customer's balance back with REVENUECAT_SECRET_KEY from your shell..."
  res=$(curl -s "https://api.revenuecat.com/v2/projects/${RC_PROJECT_ID}/customers/${FUNDED_ID}/virtual_currencies" \
    -H "Authorization: Bearer ${RC_SECRET}" || true)
  note "${res:0:300}"
  say "You should see a SCAN entry with your granted balance."
else
  note "REVENUECAT_SECRET_KEY isn't exported in this shell, so the balance wasn't read back."
  SKIPPED+=("confirm the funded customer's SCAN balance in the RevenueCat dashboard")
fi
pause "Press Enter to finish"

finish
